# Generated by Django 3.0 on 2023-10-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0004_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
